### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by 3nprob**
* Update base image to current stable bullseye-slim
* Fix python dependencies
* Optimize resulting image size 

Verification done: built image and ran `make all`

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
Thank you for this piece of maintenance.

**Comment by 3nprob** [comment]
And thank you for keeping at it :)

Just curious, have you had or seen any real-world use of this already?

**Comment by mdellweg** [comment]
I heard of real use. But i never came around to really do the git integration. Without that it's kind of worthless to me.

**Comment by 3nprob** [comment]
Left a question on the relevant issue #14 as it's not very clear exactly what's being referred to - the way I see it there's no need for git-awareness in a software like this. But I'm probably misunderstanding something.

**Pull request merged**
